### ISSUE TITLE
Missing network bindings

### ISSUE THREAD

**Issue by xavpaice** [juju/1.25-upgrade#58]
even after https://github.com/juju/1.25-upgrade/pull/57, I'm still seeing bindings missing.  In particular, for example with the Keystone charm on a config-changed hook, I see:

```
2018-02-28 02:10:00 DEBUG config-changed ERROR no network config found for binding "admin"
2018-02-28 02:10:00 DEBUG config-changed Traceback (most recent call last):
2018-02-28 02:10:00 DEBUG config-changed   File "/var/lib/juju/agents/unit-keystone-4/charm/hooks/config-changed", line 927, in <module>
2018-02-28 02:10:00 DEBUG config-changed     main()
2018-02-28 02:10:00 DEBUG config-changed   File "/var/lib/juju/agents/unit-keystone-4/charm/hooks/config-changed", line 920, in main
2018-02-28 02:10:00 DEBUG config-changed     hooks.execute(sys.argv)
2018-02-28 02:10:00 DEBUG config-changed   File "/var/lib/juju/agents/unit-keystone-4/charm/hooks/charmhelpers/core/hookenv.py", line 800, in execute
2018-02-28 02:10:00 DEBUG config-changed     self._hooks[hook_name]()
2018-02-28 02:10:00 DEBUG config-changed   File "/var/lib/juju/agents/unit-keystone-4/charm/hooks/charmhelpers/contrib/openstack/utils.py", line 1891, in wrapped_f
2018-02-28 02:10:00 DEBUG config-changed     restart_functions)
2018-02-28 02:10:00 DEBUG config-changed   File "/var/lib/juju/agents/unit-keystone-4/charm/hooks/charmhelpers/core/host.py", line 730, in restart_on_change_helper
2018-02-28 02:10:00 DEBUG config-changed     r = lambda_f()
2018-02-28 02:10:00 DEBUG config-changed   File "/var/lib/juju/agents/unit-keystone-4/charm/hooks/charmhelpers/contrib/openstack/utils.py", line 1890, in <lambda>
2018-02-28 02:10:00 DEBUG config-changed     (lambda: f(*args, **kwargs)), restart_map, stopstart,
2018-02-28 02:10:00 DEBUG config-changed   File "/var/lib/juju/agents/unit-keystone-4/charm/hooks/keystone_utils.py", line 1836, in inner_synchronize_ca_if_changed2
2018-02-28 02:10:00 DEBUG config-changed     return f(*args, **kwargs)
2018-02-28 02:10:00 DEBUG config-changed   File "/var/lib/juju/agents/unit-keystone-4/charm/hooks/charmhelpers/contrib/hardening/harden.py", line 79, in _harden_inner2
2018-02-28 02:10:00 DEBUG config-changed     return f(*args, **kwargs)
2018-02-28 02:10:00 DEBUG config-changed   File "/var/lib/juju/agents/unit-keystone-4/charm/hooks/config-changed", line 235, in config_changed
2018-02-28 02:10:00 DEBUG config-changed     cluster_joined(rid=r_id, ssl_sync_request=False)
2018-02-28 02:10:00 DEBUG config-changed   File "/var/lib/juju/agents/unit-keystone-4/charm/hooks/config-changed", line 616, in cluster_joined
2018-02-28 02:10:00 DEBUG config-changed     cidr_network=config('os-{}-network'.format(addr_type)))
2018-02-28 02:10:00 DEBUG config-changed   File "/var/lib/juju/agents/unit-keystone-4/charm/hooks/charmhelpers/contrib/network/ip.py", line 577, in get_relation_ip
2018-02-28 02:10:00 DEBUG config-changed     address = network_get_primary_address(interface)
2018-02-28 02:10:00 DEBUG config-changed   File "/var/lib/juju/agents/unit-keystone-4/charm/hooks/charmhelpers/core/hookenv.py", line 925, in inner_translate_exc2
2018-02-28 02:10:00 DEBUG config-changed     return f(*args, **kwargs)
2018-02-28 02:10:00 DEBUG config-changed   File "/var/lib/juju/agents/unit-keystone-4/charm/hooks/charmhelpers/core/hookenv.py", line 1109, in network_get_primary_address
2018-02-28 02:10:00 DEBUG config-changed     return subprocess.check_output(cmd).decode('UTF-8').strip()
2018-02-28 02:10:00 DEBUG config-changed   File "/usr/lib/python2.7/subprocess.py", line 573, in check_output
2018-02-28 02:10:00 DEBUG config-changed     raise CalledProcessError(retcode, cmd, output=output)
2018-02-28 02:10:00 DEBUG config-changed subprocess.CalledProcessError: Command '['network-get', '--primary-address', 'admin']' returned non-zero exit status 1
2018-02-28 02:10:00 ERROR juju.worker.uniter.operation runhook.go:113 hook "config-changed" failed: exit status 1
```
I can however get the bindings for the 'cluster' binding.

e.g. in a debug-hooks session:

```
root@juju-machine-23-lxc-5:/var/lib/juju/agents/unit-keystone-4/charm# network-get --primary-address admin
ERROR no network config found for binding "admin"
root@juju-machine-23-lxc-5:/var/lib/juju/agents/unit-keystone-4/charm# network-get --primary-address cluster
10.245.224.194
root@juju-machine-23-lxc-5:/var/lib/juju/agents/unit-keystone-4/charm# network-get --primary-address public
ERROR no network config found for binding "public"
```

**Comment by babbageclunk** [comment]
Fixed by #59.
